dist: bionic
language: rust

env:
  global:
    - CRATE_NAME=vmcircbuf

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - rustup self update

sudo: false

notifications:
  email: false
