dist: bionic
language: rust

env:
  global:
    - CRATE_NAME=vmcircbuf

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - env: TARGET=i686-pc-windows-msvc
      os: windows
      rust: nightly
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=x86_64-pc-windows-gnu
    - env: TARGET=x86_64-pc-windows-msvc
    - env: TARGET=i686-unknown-linux-gnu
    - env: TARGET=aarch64-unknown-linux-gnu
    - env: TARGET=arm-unknown-linux-gnueabi
    - env: TARGET=mips-unknown-linux-gnu
    - env: TARGET=mips64-unknown-linux-gnuabi64
    - env: TARGET=armv7-unknown-linux-gnueabihf
    - env: TARGET=aarch64-linux-android
    - env: TARGET=aarch64-apple-ios
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

before_install:
  - rustup self update

sudo: false

notifications:
  email: false
